### ISSUE TITLE
You have this hooked up to your personal tumblr account...

### ISSUE THREAD

**Issue by baskervald** [glebone/catumblr#1]
You have your token and everything literally in the repository. I've been looking around for a tumblr client so I decided to test this out assuming it would ask for credentials or something and I realized I was able to post to your personal tumblr (geekhost.tumblr.com -- I checked the #catumblr tag after I posted it and found it)...

You should probably take your credentials down from github man.

**Comment by glebone** [comment]
thx, just was playing around with api
